version: '3.8'

services:
  server:
    build: ./fleett-mern/server
    container_name: server
    restart: unless-stopped
    env_file:
      - ./fleett-mern/server/.env
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build: 
      context: ./fleett-mern/frontend/fleet
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
    name: car-rental-mongo-data
